// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.robot.subsystems.driveSystem;
import frc.robot.subsystems.dumperSystem;
import frc.robot.subsystems.intakeSystem;

public class autonomousCommandGroup extends SequentialCommandGroup {

    public autonomousCommandGroup(intakeSystem m_intakeSystem, dumperSystem m_dumperSystem, driveSystem m_driveSystem){

        addCommands(
            new InstantCommand(m_intakeSystem::resetIntakeState, m_intakeSystem),
            new lowerIntake(m_intakeSystem),
            new moveDumper(m_dumperSystem),
            new leaveTarmac(m_driveSystem, 84)
        );

    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
