// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.driveSystem;

public class leaveTarmac extends CommandBase {
        private final driveSystem m_driveSystem;
        private final double m_distanceInches;
        private double initalPosition;
        private double finalPosition;

    public leaveTarmac(driveSystem subsystem, double distanceInches) {
        m_driveSystem = subsystem;
        m_distanceInches = distanceInches;
        addRequirements(m_driveSystem);
    }

    @Override
    public void initialize() {
        initalPosition = m_driveSystem.getSensor();
        finalPosition = initalPosition-2048*10.7*m_distanceInches/(6*Math.PI);
    }

    @Override
    public void execute() {
        m_driveSystem.arcadeDrive(-0.5, 0);
    }

    @Override
    public void end(boolean interrupted) {
        m_driveSystem.arcadeDrive(0, 0);
    }

    @Override
    public boolean isFinished() {
        return m_driveSystem.getSensor() < finalPosition;
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
