// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.dumperSystem;

public class lowerDumper extends CommandBase {
    
    private final dumperSystem m_dumperSystem;

    public lowerDumper(dumperSystem subsystem) {
        m_dumperSystem = subsystem;
        addRequirements(m_dumperSystem);
    }

    @Override
    public void initialize() {
    }

    @Override
    public void execute() {
        m_dumperSystem.lowerDumper();
    }

    @Override
    public void end(boolean interrupted) {
        m_dumperSystem.stopDumperMotor();
    }

    @Override
    public boolean isFinished() {
        return m_dumperSystem.isDumperLowered();
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
