// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.RobotContainer;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.motorcontrol.MotorControllerGroup;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class driveSystem extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonFX m_leftFront;
    private WPI_TalonFX m_leftBack;
    private MotorControllerGroup motorControllerGroup1;
    private WPI_TalonFX m_rightFront;
    private WPI_TalonFX m_rightBack;
    private MotorControllerGroup motorControllerGroup2;
    private DifferentialDrive differentialDrive1;
    private double joystickY;
    private double joystickZ;
    private final Joystick joystick0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public driveSystem() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        m_leftFront = new WPI_TalonFX(1, "rio");
        m_leftBack = new WPI_TalonFX(2, "rio");

        motorControllerGroup1 = new MotorControllerGroup(m_leftFront, m_leftBack  );
        addChild("Motor Controller Group 1",motorControllerGroup1);
        
        m_rightFront = new WPI_TalonFX(3, "rio");
        m_rightBack = new WPI_TalonFX(4, "rio");

        motorControllerGroup2 = new MotorControllerGroup(m_rightFront, m_rightBack  );
        addChild("Motor Controller Group 2",motorControllerGroup2);

        differentialDrive1 = new DifferentialDrive(motorControllerGroup1, motorControllerGroup2);
        addChild("Differential Drive 1",differentialDrive1);
        differentialDrive1.setSafetyEnabled(true);
        differentialDrive1.setExpiration(0.1);
        differentialDrive1.setMaxOutput(0.3);

        joystick0 = RobotContainer.getInstance().getrobotController();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        joystickY = joystick0.getY();
        joystickY = joystickY*joystickY*joystickY;
        joystickZ = joystick0.getZ();
        joystickZ = joystickZ*joystickZ*joystickZ;

        differentialDrive1.arcadeDrive(joystickY, joystickZ);
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

